export const authTypes = {
    SIGNUP_REQUEST:'SIGNUP_REQUEST',
    SIGNUP_SUCCESS:'SIGNUP_SUCCESS',
    SIGNUP_FAILURE:'SIGNUP_FAILURE',
    LOGIN_REQUEST:'LOGIN_REQUEST',
    LOGIN_SUCCESS:'LOGIN_SUCCESS',
    LOGIN_FAILURE:'LOGIN_FAILURE',
    LOGOUT_REQUEST:'LOGOUT_REQUEST',
    LOGOUT_SUCCESS:'LOGOUT_SUCCESS',
    LOGOUT_FAILURE:'LOGOUT_FAILURE',
}